name: lewi
favicon: null
layout_spectrum: 0.74254
typography_spectrum: 0.33358
title: Studio Black
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#181818'
    - '#f1f1f1'
    - '#444444'
    - '#a6b0b2'
    - '#008483'
  brandStrength: 0.75
  lightness: 0.9770035699475557
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
